/**
 * FK-2 — Structured advice types (no product SKU recommendations).
 */
export const FashionAdviceType = {
  PRESERVE_LOOK: 'PRESERVE_LOOK',
  REDUCE_CONTRAST: 'REDUCE_CONTRAST',
  INCREASE_CONTRAST: 'INCREASE_CONTRAST',
  INCREASE_FORMALITY: 'INCREASE_FORMALITY',
  DECREASE_FORMALITY: 'DECREASE_FORMALITY',
  BALANCE_COLOR: 'BALANCE_COLOR',
  BALANCE_VOLUME: 'BALANCE_VOLUME',
  SIMPLIFY_ACCESSORIES: 'SIMPLIFY_ACCESSORIES',
  ADD_ACCESSORY: 'ADD_ACCESSORY',
  REMOVE_ACCESSORY: 'REMOVE_ACCESSORY',
  CHANGE_ACCESSORY: 'CHANGE_ACCESSORY',
  CHANGE_ACCESSORY_DIRECTION: 'CHANGE_ACCESSORY_DIRECTION',
  CHANGE_SHOE_DIRECTION: 'CHANGE_SHOE_DIRECTION',
  CHANGE_BAG_DIRECTION: 'CHANGE_BAG_DIRECTION',
  JEWELRY_DIRECTION: 'JEWELRY_DIRECTION',
  NEUTRALIZE_SUPPORTING_ELEMENTS: 'NEUTRALIZE_SUPPORTING_ELEMENTS',
  PRESERVE_SUPPORTING_ELEMENTS: 'PRESERVE_SUPPORTING_ELEMENTS',
  FABRIC_DIRECTION: 'FABRIC_DIRECTION',
  PRESERVE_VOLUME_CONTRAST: 'PRESERVE_VOLUME_CONTRAST',
  SIMPLIFY_TEXTURE: 'SIMPLIFY_TEXTURE',
  PRESERVE_TEXTURE_CONTRAST: 'PRESERVE_TEXTURE_CONTRAST',
  ADJUST_LAYERING_DIRECTION: 'ADJUST_LAYERING_DIRECTION',
  INCREASE_STRUCTURE: 'INCREASE_STRUCTURE',
  INCREASE_FLUIDITY: 'INCREASE_FLUIDITY',
  SIMPLIFY_SILHOUETTE: 'SIMPLIFY_SILHOUETTE',
  PRESERVE_STATEMENT_SILHOUETTE: 'PRESERVE_STATEMENT_SILHOUETTE',
  ADJUST_LENGTH_RELATIONSHIP: 'ADJUST_LENGTH_RELATIONSHIP',
  OCCASION_ADJUSTMENT: 'OCCASION_ADJUSTMENT',
  CLARIFICATION_REQUIRED: 'CLARIFICATION_REQUIRED',
  NO_CHANGE_NEEDED: 'NO_CHANGE_NEEDED',
} as const;

export type FashionAdviceType =
  (typeof FashionAdviceType)[keyof typeof FashionAdviceType];

export const ALL_FASHION_ADVICE_TYPES: readonly FashionAdviceType[] =
  Object.freeze(Object.values(FashionAdviceType));

export function isFashionAdviceType(
  value: unknown,
): value is FashionAdviceType {
  return (
    typeof value === 'string' &&
    (ALL_FASHION_ADVICE_TYPES as readonly string[]).includes(value)
  );
}
