/// Central route names for Mira.
abstract final class AppRoutes {
  static const splash = '/';
  static const onboarding = '/onboarding';
  static const login = '/login';
  /// Same screen as [login] — phone OTP handles sign-up and sign-in.
  static const register = '/register';
  static const dashboard = '/dashboard';
  static const profile = '/profile';
  static const settings = '/settings';
  static const analysis = '/analysis';
  static const history = '/history';
  static const points = '/points';
  static const tips = '/tips';
  static const newAnalysis = '/new-analysis';
  static const skinScan = '/skin-scan';
  static const skinResult = '/skin-result';
  static const miraBeautyReport = '/mira-beauty-report';
  static const beautyProgress = '/beauty-progress';
  static const skinRoutine = '/skin-routine';
  static const privacyConsent = '/privacy-consent';
  static const privacyPolicy = '/privacy-policy';
  static const outfitLiveCapture = '/outfit-live-capture';
  static const outfitUpload = '/outfit-upload';
  static const outfitCamera = '/outfit-camera';
  static const occasionSelect = '/occasion-select';
  static const outfitResult = '/outfit-result';
  static const miraStyleReport = '/mira-style-report';
  static const outfitHistory = '/outfit-history';
  static const recommendations = '/recommendations';
  static const recommendationHistory = '/recommendation-history';
  static const miraAdvisor = '/mira-advisor';
  static const paywall = '/paywall';
  static const packageStore = '/package-store';
  static const manageSubscription = '/manage-subscription';
  static const feedback = '/feedback';
  static const notificationsSettings = '/settings-notifications';
  static const help = '/help';
  static const about = '/about';
  static const discover = '/discover';
  static const discoverList = '/discover-list';
  static const productDetail = '/product-detail';
  static const serviceDetail = '/service-detail';
}
