// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtGhM0OZyWhcsQ6VUdEdMtAgixCV2NnKw',
    appId: '1:399849748934:web:6201816764fbe14097dac7',
    messagingSenderId: '399849748934',
    projectId: 'mirra-14b0e',
    authDomain: 'mirra-14b0e.firebaseapp.com',
    storageBucket: 'mirra-14b0e.firebasestorage.app',
    measurementId: 'G-FVFMP7TS5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC82sslwobSzC1Bhl3_Un00NJndTHurJfo',
    appId: '1:399849748934:android:1d531f1bf71ed3f097dac7',
    messagingSenderId: '399849748934',
    projectId: 'mirra-14b0e',
    storageBucket: 'mirra-14b0e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4p9rd5NwT1Fm_zY6s-kXA1EilP8M4Eew',
    appId: '1:399849748934:ios:25ac117e432b31f497dac7',
    messagingSenderId: '399849748934',
    projectId: 'mirra-14b0e',
    storageBucket: 'mirra-14b0e.firebasestorage.app',
    iosClientId: '399849748934-3u8tj6pc38f3l4at6hmmapkdgg031ej6.apps.googleusercontent.com',
    iosBundleId: 'app.mira.beauty',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4p9rd5NwT1Fm_zY6s-kXA1EilP8M4Eew',
    appId: '1:399849748934:ios:25ac117e432b31f497dac7',
    messagingSenderId: '399849748934',
    projectId: 'mirra-14b0e',
    storageBucket: 'mirra-14b0e.firebasestorage.app',
    iosClientId: '399849748934-3u8tj6pc38f3l4at6hmmapkdgg031ej6.apps.googleusercontent.com',
    iosBundleId: 'app.mira.beauty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtGhM0OZyWhcsQ6VUdEdMtAgixCV2NnKw',
    appId: '1:399849748934:web:34169347d2bd135997dac7',
    messagingSenderId: '399849748934',
    projectId: 'mirra-14b0e',
    authDomain: 'mirra-14b0e.firebaseapp.com',
    storageBucket: 'mirra-14b0e.firebasestorage.app',
    measurementId: 'G-TWSGNYR5ND',
  );
}
