// ignore_for_file: avoid_print

import 'dart:convert';
import 'dart:io';

/// Syncs assets/fashion/*.json → generated Dart catalog + color + compatibility data.
void main() {
  final catalogFile = File('assets/fashion/catalog.json');
  if (!catalogFile.existsSync()) {
    stderr.writeln('Missing assets/fashion/catalog.json');
    exit(1);
  }

  final catalog = jsonDecode(catalogFile.readAsStringSync()) as Map<String, dynamic>;
  final pieces = (catalog['pieces'] as List<dynamic>).cast<Map<String, dynamic>>();
  final colors = _loadColors();
  final missing = <String>[];
  final warnings = <String>[];

  for (final piece in pieces) {
    final file = piece['file'] as String;
    final path = 'assets/fashion/$file';
    if (!File(path).existsSync()) {
      missing.add(path);
    } else {
      _checkResolution(path, warnings);
    }

    final colorId = piece['colorId'] as String?;
    if (colorId != null && colors.containsKey(colorId)) {
      piece['colorHex'] = colors[colorId]!['hex'];
    }
  }

  if (missing.isNotEmpty) {
    stderr.writeln('Missing PNG files:');
    for (final m in missing) {
      stderr.writeln('  - $m');
    }
    exit(1);
  }

  for (final w in warnings) {
    print('WARN: $w');
  }

  final catalogOut = File('lib/features/outfit_analysis/domain/catalog/fashion_asset_catalog_data.dart');
  catalogOut.writeAsStringSync(_generateCatalogDart(pieces));

  final colorOut = File('lib/features/outfit_analysis/domain/catalog/fashion_color_library_data.dart');
  colorOut.writeAsStringSync(_generateColorDart(colors));

  final compatOut = File('lib/features/outfit_analysis/domain/catalog/fashion_compatibility_data.dart');
  compatOut.writeAsStringSync(_generateCompatibilityDart());

  final graphOut = File('lib/features/outfit_analysis/domain/intelligence/fashion_knowledge_graph_data.dart');
  graphOut.writeAsStringSync(_generateGraphDart());

  final trendsOut = File('lib/features/outfit_analysis/domain/intelligence/fashion_trends_data.dart');
  trendsOut.writeAsStringSync(_generateTrendsDart());

  final embedOut = File('lib/features/outfit_analysis/domain/intelligence/fashion_embedding_data.dart');
  embedOut.writeAsStringSync(_generateEmbeddingDart(pieces));

  print('✓ Synced ${pieces.length} pieces → ${catalogOut.path}');
  print('✓ Synced ${colors.length} colors → ${colorOut.path}');
  print('✓ Synced compatibility pairs → ${compatOut.path}');
  print('✓ Synced knowledge graph → ${graphOut.path}');
  print('✓ Synced trends → ${trendsOut.path}');
  print('✓ Synced embeddings → ${embedOut.path}');
  if (warnings.isNotEmpty) {
    print('  ${warnings.length} resolution warnings (replace placeholders with 2000×2000 PNGs)');
  }
}

Map<String, Map<String, dynamic>> _loadColors() {
  final file = File('assets/fashion/colors.json');
  if (!file.existsSync()) return {};
  final json = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
  return (json['colors'] as Map<String, dynamic>).map(
    (k, v) => MapEntry(k, (v as Map<String, dynamic>)),
  );
}

void _checkResolution(String path, List<String> warnings) {
  final bytes = File(path).readAsBytesSync();
  if (bytes.length < 50000) {
    warnings.add('$path is ${(bytes.length / 1024).toStringAsFixed(1)}KB — likely placeholder (<50KB)');
  }
}

String _escape(String s) => s.replaceAll("'", "\\'").replaceAll('\n', ' ');

String _stringList(dynamic raw) {
  final list = raw is List ? raw : [raw];
  return list.map((e) => "'${_escape(e.toString())}'").join(', ');
}

String _generateCatalogDart(List<Map<String, dynamic>> pieces) {
  final buffer = StringBuffer('''
// GENERATED by scripts/sync_fashion_catalog.dart — do not edit by hand.
// Source: assets/fashion/catalog.json

import '../../../../core/ai/models/mira_occasion.dart';
import '../entities/suggested_piece_model.dart';
import 'fashion_asset_catalog.dart';
import 'fashion_catalog_types.dart';

''');

  buffer.writeln('const catalogPieces = <CatalogPiece>[');
  for (final p in pieces) {
    final occasions = (p['occasion'] as List<dynamic>)
        .map((o) => _occasionEnum(o as String))
        .join(', ');
    final colorTags = (p['colorTags'] as List<dynamic>).map((c) => "'${_escape(c as String)}'").join(', ');
    final seasons = (p['season'] as List<dynamic>).map((s) => "'$s'").join(', ');
    final styles = _stringList(p['styles'] ?? [p['style'] ?? 'luxury']);
    final archetypes = _stringList(p['archetypes'] ?? const []);
    final compatible = _stringList(p['compatibleWith'] ?? const []);
    final recommendedFor = _stringList(p['recommendedFor'] ?? const ['all']);
    final extendedOccasions = _stringList(p['extendedOccasions'] ?? const []);
    final kind = p['kind'] == 'clothing' ? 'CatalogKind.clothing' : 'CatalogKind.accessory';
    final scores = p['scores'] as Map<String, dynamic>? ?? {};
    final angles = p['angles'] as Map<String, dynamic>? ?? {'front': p['file']};
    final prompts = p['prompts'] as Map<String, dynamic>?;

    buffer.writeln('  CatalogPiece(');
    buffer.writeln("    id: '${p['id']}',");
    buffer.writeln("    category: '${p['category']}',");
    buffer.writeln("    subcategory: '${p['subcategory'] ?? ''}',");
    buffer.writeln("    asset: '\${FashionAssetCatalog.basePath}/${p['file']}',");
    buffer.writeln("    titleAr: '${_escape(p['titleAr'] as String)}',");
    buffer.writeln("    styleTag: '${p['styleTag']}',");
    buffer.writeln("    colorHex: '${p['colorHex']}',");
    buffer.writeln("    colorId: ${p['colorId'] != null ? "'${p['colorId']}'" : 'null'},");
    buffer.writeln("    secondaryColorId: ${p['secondaryColorId'] != null ? "'${p['secondaryColorId']}'" : 'null'},");
    buffer.writeln('    colorTags: const [$colorTags],');
    buffer.writeln('    seasons: const [$seasons],');
    buffer.writeln('    styles: const [$styles],');
    buffer.writeln('    archetypes: const [$archetypes],');
    buffer.writeln("    brandStyle: '${p['brandStyle']}',");
    buffer.writeln("    priceLevel: '${p['priceLevel']}',");
    buffer.writeln("    gender: '${p['gender'] ?? 'female'}',");
    buffer.writeln("    material: '${p['material'] ?? ''}',");
    buffer.writeln("    fit: '${p['fit'] ?? 'regular'}',");
    buffer.writeln("    sleeve: '${p['sleeve'] ?? 'none'}',");
    buffer.writeln("    texture: '${p['texture'] ?? 'matte'}',");
    buffer.writeln("    pattern: '${p['pattern'] ?? 'solid'}',");
    buffer.writeln("    countryStyle: '${p['countryStyle'] ?? 'European'}',");
    buffer.writeln('    occasions: const [$occasions],');
    buffer.writeln('    minFormality: ${p['minFormality']},');
    buffer.writeln('    maxFormality: ${p['maxFormality']},');
    buffer.writeln("    whyAr: '${_escape(p['whyAr'] as String)}',");
    buffer.writeln('    kind: $kind,');
    buffer.writeln('    compatibleWith: const [$compatible],');
    buffer.writeln('    recommendedFor: const [$recommendedFor],');
    buffer.writeln('    extendedOccasions: const [$extendedOccasions],');
    buffer.writeln('    scores: FashionPieceScores(');
    buffer.writeln('      luxury: ${scores['luxury'] ?? 0},');
    buffer.writeln('      formal: ${scores['formal'] ?? 0},');
    buffer.writeln('      minimal: ${scores['minimal'] ?? 0},');
    buffer.writeln('      business: ${scores['business'] ?? 0},');
    buffer.writeln('    ),');
    buffer.writeln('    angles: PieceAngles(');
    buffer.writeln("      front: '\${FashionAssetCatalog.basePath}/${angles['front'] ?? p['file']}',");
    if (angles['back'] != null) {
      buffer.writeln("      back: '\${FashionAssetCatalog.basePath}/${angles['back']}',");
    }
    if (angles['angle45'] != null) {
      buffer.writeln("      angle45: '\${FashionAssetCatalog.basePath}/${angles['angle45']}',");
    }
    if (angles['detail'] != null) {
      buffer.writeln("      detail: '\${FashionAssetCatalog.basePath}/${angles['detail']}',");
    }
    if (angles['fabric'] != null) {
      buffer.writeln("      fabric: '\${FashionAssetCatalog.basePath}/${angles['fabric']}',");
    }
    buffer.writeln('    ),');
    if (prompts != null) {
      buffer.writeln('    prompts: PiecePrompts(');
      buffer.writeln("      generation: '${_escape(prompts['generation'] as String? ?? '')}',");
      buffer.writeln("      editing: '${_escape(prompts['editing'] as String? ?? '')}',");
      buffer.writeln("      backgroundRemoval: '${_escape(prompts['backgroundRemoval'] as String? ?? '')}',");
      buffer.writeln('    ),');
    }
    buffer.writeln('  ),');
  }
  buffer.writeln('];');
  buffer.writeln('');
  return buffer.toString();
}

String _generateColorDart(Map<String, Map<String, dynamic>> colors) {
  final buffer = StringBuffer('''
// GENERATED by scripts/sync_fashion_catalog.dart — do not edit by hand.
// Source: assets/fashion/colors.json

import 'fashion_catalog_types.dart';

const colorEntries = <String, FashionColorEntry>{
''');

  for (final entry in colors.entries) {
    final c = entry.value;
    final lab = (c['lab'] as List<dynamic>).map((e) => e.toString()).join(', ');
    final hsv = (c['hsv'] as List<dynamic>).map((e) => e.toString()).join(', ');
    buffer.writeln("  '${entry.key}': FashionColorEntry(");
    buffer.writeln("    id: '${entry.key}',");
    buffer.writeln("    name: '${c['name']}',");
    buffer.writeln("    nameAr: '${c['nameAr']}',");
    buffer.writeln("    hex: '${c['hex']}',");
    buffer.writeln('    lab: const [$lab],');
    buffer.writeln('    hsv: const [$hsv],');
    buffer.writeln('  ),');
  }
  buffer.writeln('};');
  buffer.writeln('');
  return buffer.toString();
}

String _generateCompatibilityDart() {
  final file = File('assets/fashion/compatibility.json');
  final json = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
  final pairs = (json['pairs'] as List<dynamic>).cast<Map<String, dynamic>>();

  final buffer = StringBuffer('''
// GENERATED by scripts/sync_fashion_catalog.dart — do not edit by hand.
// Source: assets/fashion/compatibility.json

import 'fashion_compatibility_engine.dart';

const compatibilityByAnchor = <String, CompatibilityPair>{
''');

  for (final pair in pairs) {
    final ids = (pair['compatibleIds'] as List<dynamic>).map((e) => "'$e'").join(', ');
    buffer.writeln("  '${pair['anchorId']}': CompatibilityPair(");
    buffer.writeln("    anchorId: '${pair['anchorId']}',");
    buffer.writeln('    compatibleIds: const [$ids],');
    buffer.writeln("    whyAr: '${_escape(pair['whyAr'] as String)}',");
    buffer.writeln('  ),');
  }
  buffer.writeln('};');
  buffer.writeln('');
  return buffer.toString();
}

String _occasionEnum(String id) {
  return switch (id) {
    'wedding' => 'MiraOccasion.wedding',
    'work' => 'MiraOccasion.work',
    'casual' => 'MiraOccasion.casual',
    'university' => 'MiraOccasion.university',
    'evening' => 'MiraOccasion.evening',
    'eid' => 'MiraOccasion.eid',
    'interview' => 'MiraOccasion.interview',
    _ => 'MiraOccasion.casual',
  };
}

String _generateGraphDart() {
  final file = File('assets/fashion/knowledge_graph.json');
  final json = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
  final edges = (json['edges'] as List<dynamic>).cast<Map<String, dynamic>>();

  final byAnchor = <String, List<Map<String, dynamic>>>{};
  for (final e in edges) {
    final from = e['from'] as String;
    byAnchor.putIfAbsent(from, () => []).add(e);
  }

  final buffer = StringBuffer('''
// GENERATED by scripts/sync_fashion_catalog.dart — do not edit by hand.
// Source: assets/fashion/knowledge_graph.json

import 'fashion_knowledge_graph.dart';

const graphEdgesFrom = <String, List<GraphEdge>>{
''');

  for (final entry in byAnchor.entries) {
    buffer.writeln("  '${entry.key}': const [");
    for (final e in entry.value) {
      buffer.writeln('    GraphEdge(');
      buffer.writeln("      from: '${e['from']}',");
      buffer.writeln("      to: '${e['to']}',");
      buffer.writeln("      relation: '${e['relation']}',");
      buffer.writeln('      weight: ${e['weight']},');
      buffer.writeln("      whyAr: '${_escape(e['whyAr'] as String)}',");
      buffer.writeln('    ),');
    }
    buffer.writeln('  ],');
  }
  buffer.writeln('};');
  buffer.writeln('');
  return buffer.toString();
}

String _generateTrendsDart() {
  final file = File('assets/fashion/fashion_trends.json');
  final json = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;

  final colors = (json['colors'] as List<dynamic>).cast<Map<String, dynamic>>();
  final styles = (json['styles'] as List<dynamic>).cast<Map<String, dynamic>>();
  final materials = (json['materials'] as List<dynamic>).cast<Map<String, dynamic>>();

  final buffer = StringBuffer('''
// GENERATED by scripts/sync_fashion_catalog.dart — do not edit by hand.
// Source: assets/fashion/fashion_trends.json

import 'fashion_trend_engine.dart';

const trendColors = <TrendColor>[
''');

  for (final c in colors) {
    buffer.writeln('  TrendColor(');
    buffer.writeln("    id: '${c['id']}',");
    buffer.writeln("    nameAr: '${c['nameAr']}',");
    buffer.writeln("    hex: '${c['hex']}',");
    buffer.writeln('    weight: ${c['weight']},');
    buffer.writeln('  ),');
  }
  buffer.writeln('];');
  buffer.writeln('');
  buffer.writeln('const trendStyles = <TrendStyle>[');
  for (final s in styles) {
    buffer.writeln('  TrendStyle(');
    buffer.writeln("    id: '${s['id']}',");
    buffer.writeln("    nameAr: '${s['nameAr']}',");
    buffer.writeln('    weight: ${s['weight']},');
    buffer.writeln('  ),');
  }
  buffer.writeln('];');
  buffer.writeln('');
  buffer.writeln('const trendMaterials = <TrendMaterial>[');
  for (final m in materials) {
    buffer.writeln('  TrendMaterial(');
    buffer.writeln("    id: '${m['id']}',");
    buffer.writeln('    weight: ${m['weight']},');
    buffer.writeln('  ),');
  }
  buffer.writeln('];');
  buffer.writeln('');
  return buffer.toString();
}

String _generateEmbeddingDart(List<Map<String, dynamic>> pieces) {
  const dim = 512;
  final buffer = StringBuffer('''
// GENERATED by scripts/sync_fashion_catalog.dart — do not edit by hand.
// Stub 512D vectors — replace with ML embeddings in production.

const pieceEmbeddings = <String, List<double>>{
''');

  for (final p in pieces) {
    final id = p['id'] as String;
    final seed = id.hashCode;
    final vec = List.generate(dim, (i) {
      final v = ((seed * (i + 1) * 9973) % 10000) / 5000.0 - 1.0;
      return v.toStringAsFixed(6);
    });
    buffer.writeln("  '$id': const [${vec.join(', ')}],");
  }
  buffer.writeln('};');
  buffer.writeln('');
  return buffer.toString();
}
