// GENERATED by scripts/sync_fashion_catalog.dart — do not edit by hand.
// Source: assets/fashion/fashion_trends.json

import 'fashion_trend_engine.dart';

const trendColors = <TrendColor>[
  TrendColor(
    id: 'mocha',
    nameAr: 'موكا',
    hex: '#8B7355',
    weight: 0.95,
  ),
  TrendColor(
    id: 'burgundy',
    nameAr: 'نبيتي',
    hex: '#722F37',
    weight: 0.88,
  ),
  TrendColor(
    id: 'olive',
    nameAr: 'زيتوني',
    hex: '#6B7050',
    weight: 0.82,
  ),
  TrendColor(
    id: 'chocolate',
    nameAr: 'شوكولاتة',
    hex: '#4A3728',
    weight: 0.8,
  ),
  TrendColor(
    id: 'blush',
    nameAr: 'وردي ناعم',
    hex: '#E8C4C4',
    weight: 0.75,
  ),
];

const trendStyles = <TrendStyle>[
  TrendStyle(
    id: 'quiet_luxury',
    nameAr: 'رفاهية هادئة',
    weight: 0.98,
  ),
  TrendStyle(
    id: 'old_money',
    nameAr: 'أناقة كلاسيكية',
    weight: 0.94,
  ),
  TrendStyle(
    id: 'minimal',
    nameAr: 'مينimal',
    weight: 0.92,
  ),
  TrendStyle(
    id: 'coastal_grandmother',
    nameAr: 'ساحلي كلاسيكي',
    weight: 0.7,
  ),
  TrendStyle(
    id: 'power_dressing',
    nameAr: 'أناقة مهنية',
    weight: 0.85,
  ),
];

const trendMaterials = <TrendMaterial>[
  TrendMaterial(
    id: 'linen',
    weight: 0.9,
  ),
  TrendMaterial(
    id: 'silk',
    weight: 0.85,
  ),
  TrendMaterial(
    id: 'cashmere',
    weight: 0.78,
  ),
  TrendMaterial(
    id: 'leather',
    weight: 0.82,
  ),
];

