// GENERATED by scripts/sync_fashion_catalog.dart — do not edit by hand.
// Source: assets/fashion/colors.json

import 'fashion_catalog_types.dart';

const colorEntries = <String, FashionColorEntry>{
  'beige_linen': FashionColorEntry(
    id: 'beige_linen',
    name: 'beige',
    nameAr: 'بيج',
    hex: '#E8D6C0',
    lab: const [86.2, 2.1, 18.4],
    hsv: const [32, 18, 91],
  ),
  'cream_soft': FashionColorEntry(
    id: 'cream_soft',
    name: 'cream',
    nameAr: 'كريمي',
    hex: '#F5EDE0',
    lab: const [93.5, 1.2, 9.8],
    hsv: const [38, 10, 96],
  ),
  'black_pure': FashionColorEntry(
    id: 'black_pure',
    name: 'black',
    nameAr: 'أسود',
    hex: '#1A1A1A',
    lab: const [8.5, 0.1, -0.2],
    hsv: const [0, 0, 10],
  ),
  'navy_deep': FashionColorEntry(
    id: 'navy_deep',
    name: 'navy',
    nameAr: 'كحلي',
    hex: '#1E2A4A',
    lab: const [18.2, 5.4, -22.1],
    hsv: const [222, 58, 29],
  ),
  'ivory_warm': FashionColorEntry(
    id: 'ivory_warm',
    name: 'ivory',
    nameAr: 'عاجي',
    hex: '#F7F2EA',
    lab: const [95.8, 0.8, 6.2],
    hsv: const [40, 6, 97],
  ),
  'gray_soft': FashionColorEntry(
    id: 'gray_soft',
    name: 'gray',
    nameAr: 'رمادي',
    hex: '#C8C4BE',
    lab: const [79.4, 0.5, 2.1],
    hsv: const [40, 5, 78],
  ),
  'silver_metal': FashionColorEntry(
    id: 'silver_metal',
    name: 'silver',
    nameAr: 'فضي',
    hex: '#C0C0C8',
    lab: const [78.2, 0.2, -2.4],
    hsv: const [240, 5, 78],
  ),
  'gold_warm': FashionColorEntry(
    id: 'gold_warm',
    name: 'gold',
    nameAr: 'ذهبي',
    hex: '#C9A962',
    lab: const [68.4, 2.8, 38.2],
    hsv: const [42, 52, 79],
  ),
  'nude_heel': FashionColorEntry(
    id: 'nude_heel',
    name: 'nude',
    nameAr: 'نود',
    hex: '#E3C4A8',
    lab: const [80.1, 8.2, 18.6],
    hsv: const [28, 26, 89],
  ),
  'pearl_white': FashionColorEntry(
    id: 'pearl_white',
    name: 'pearl',
    nameAr: 'لؤلؤي',
    hex: '#F5F0E8',
    lab: const [94.2, 0.5, 4.8],
    hsv: const [38, 8, 96],
  ),
  'brown_tortoise': FashionColorEntry(
    id: 'brown_tortoise',
    name: 'brown',
    nameAr: 'بني',
    hex: '#6B4A32',
    lab: const [35.8, 12.4, 22.1],
    hsv: const [25, 54, 42],
  ),
  'blush_lilac': FashionColorEntry(
    id: 'blush_lilac',
    name: 'lilac',
    nameAr: 'لافندر',
    hex: '#EDE4F0',
    lab: const [90.8, 4.2, -4.8],
    hsv: const [285, 8, 94],
  ),
};

